ALLOWED_EXTENSIONS = {'txt', 'prj', 'sdat', 'sgrd'}
DRASTIC_DATA_FOLDER = "/home/rodrigo/data/"
DRASTIC_DATA_FOLDER_D = DRASTIC_DATA_FOLDER + "d/"
DRASTIC_DATA_FOLDER_D_INPUT = DRASTIC_DATA_FOLDER_D + "input/"
DRASTIC_DATA_FOLDER_D_PROCESS = DRASTIC_DATA_FOLDER_D + "process/"