ALLOWED_EXTENSIONS = {'txt', 'prj', 'sdat', 'sgrd', 'rar', 'cpg', 'dbf', 'qpj', 'shp', 'shx'}


DRASTIC_DATA_FOLDER = "/home/rodrigo/data/"
FOLDER_INPUT = "input/"
FOLDER_PROCESS = "process/"
FOLDER_RESULT = "result/"

DRASTIC_DATA_FOLDER_D = DRASTIC_DATA_FOLDER + "d/"
DRASTIC_DATA_FOLDER_D_INPUT = DRASTIC_DATA_FOLDER_D + FOLDER_INPUT
DRASTIC_DATA_FOLDER_D_PROCESS = DRASTIC_DATA_FOLDER_D + FOLDER_PROCESS
DRASTIC_DATA_FOLDER_D_RESULT = DRASTIC_DATA_FOLDER_D + FOLDER_RESULT
D_RATINGS = [0.0, 1.5, 10.0,
    1.5, 4.6, 9.0,
    4.6, 9.1, 7.0,
    9.1, 15.2, 5.0,
    15.2, 22.9, 3.0,
    22.9, 30.5, 2.0,
    30.5, 200.0, 1.0]

DRASTIC_DATA_FOLDER_R = DRASTIC_DATA_FOLDER + "r/"
DRASTIC_DATA_FOLDER_R_INPUT = DRASTIC_DATA_FOLDER_R + FOLDER_INPUT
DRASTIC_DATA_FOLDER_R_PROCESS = DRASTIC_DATA_FOLDER_R + FOLDER_PROCESS
DRASTIC_DATA_FOLDER_R_RESULT = DRASTIC_DATA_FOLDER_R + FOLDER_RESULT
R_RATINGS = [0.0, 51.0, 1.0,
    51.0, 102.0, 3.0,
    102.0, 178.0, 6.0,
    178.0, 254.0, 8.0,
    254.0, 1000.0, 9.0]

DRASTIC_DATA_FOLDER_A = DRASTIC_DATA_FOLDER + "a/"
DRASTIC_DATA_FOLDER_A_INPUT = DRASTIC_DATA_FOLDER_A + FOLDER_INPUT
DRASTIC_DATA_FOLDER_A_PROCESS = DRASTIC_DATA_FOLDER_A + FOLDER_PROCESS
DRASTIC_DATA_FOLDER_A_RESULT = DRASTIC_DATA_FOLDER_A + FOLDER_RESULT
A_RATINGS = [0.0, 1.5, 10.0,
    1.5, 4.6, 9.0,
    4.6, 9.1, 7.0,
    9.1, 15.2, 5.0,
    15.2, 22.9, 3.0,
    22.9, 30.5, 2.0,
    30.5, 200.0, 1.0]

DRASTIC_DATA_FOLDER_S = DRASTIC_DATA_FOLDER + "s/"
DRASTIC_DATA_FOLDER_S_INPUT = DRASTIC_DATA_FOLDER_S + FOLDER_INPUT
DRASTIC_DATA_FOLDER_S_PROCESS = DRASTIC_DATA_FOLDER_S + FOLDER_PROCESS
DRASTIC_DATA_FOLDER_S_RESULT = DRASTIC_DATA_FOLDER_S + FOLDER_RESULT

DRASTIC_DATA_FOLDER_T = DRASTIC_DATA_FOLDER + "t/"
DRASTIC_DATA_FOLDER_T_INPUT = DRASTIC_DATA_FOLDER_T + FOLDER_INPUT
DRASTIC_DATA_FOLDER_T_PROCESS = DRASTIC_DATA_FOLDER_T + FOLDER_PROCESS
DRASTIC_DATA_FOLDER_T_RESULT = DRASTIC_DATA_FOLDER_T + FOLDER_RESULT

DRASTIC_DATA_FOLDER_I = DRASTIC_DATA_FOLDER + "i/"
DRASTIC_DATA_FOLDER_I_INPUT = DRASTIC_DATA_FOLDER_I + FOLDER_INPUT
DRASTIC_DATA_FOLDER_I_PROCESS = DRASTIC_DATA_FOLDER_I + FOLDER_PROCESS
DRASTIC_DATA_FOLDER_I_RESULT = DRASTIC_DATA_FOLDER_I + FOLDER_RESULT

DRASTIC_DATA_FOLDER_C = DRASTIC_DATA_FOLDER + "c/"
DRASTIC_DATA_FOLDER_C_INPUT = DRASTIC_DATA_FOLDER_C + FOLDER_INPUT
DRASTIC_DATA_FOLDER_C_PROCESS = DRASTIC_DATA_FOLDER_C + FOLDER_PROCESS
DRASTIC_DATA_FOLDER_C_RESULT = DRASTIC_DATA_FOLDER_C + FOLDER_RESULT

DRASTIC_DATA_FOLDER_DRASTIC = DRASTIC_DATA_FOLDER + "drastic/"
DRASTIC_DATA_FOLDER_DRASTIC_PROCESS = DRASTIC_DATA_FOLDER_DRASTIC + FOLDER_PROCESS
DRASTIC_DATA_FOLDER_DRASTIC_RESULT = DRASTIC_DATA_FOLDER_DRASTIC + FOLDER_RESULT