ALLOWED_EXTENSIONS = {'txt', 'prj', 'sdat', 'sgrd', 'rar', 'cpg', 'dbf', 'qpj', 'shp', 'shx'}

GVTOLL_WEB_DATA_FOLDER = "/home/rodrigo/data/"

DRASTIC_DATA_FOLDER = GVTOLL_WEB_DATA_FOLDER + "drastic/"
GOD_DATA_FOLDER = GVTOLL_WEB_DATA_FOLDER + "god/"
SI_DATA_FOLDER = GVTOLL_WEB_DATA_FOLDER + "si/"

FOLDER_INPUT = "input/"
FOLDER_PROCESS = "process/"
FOLDER_RESULT = "result/"

DRASTIC_DATA_FOLDER_D = DRASTIC_DATA_FOLDER + "d/"
DRASTIC_DATA_D_INPUT = DRASTIC_DATA_FOLDER_D + FOLDER_INPUT
DRASTIC_DATA_D_PROCESS = DRASTIC_DATA_FOLDER_D + FOLDER_PROCESS
DRASTIC_DATA_D_RESULT = DRASTIC_DATA_FOLDER_D + FOLDER_RESULT

DRASTIC_DATA_FOLDER_R = DRASTIC_DATA_FOLDER + "r/"
DRASTIC_DATA_R_INPUT = DRASTIC_DATA_FOLDER_R + FOLDER_INPUT
DRASTIC_DATA_R_PROCESS = DRASTIC_DATA_FOLDER_R + FOLDER_PROCESS
DRASTIC_DATA_R_RESULT = DRASTIC_DATA_FOLDER_R + FOLDER_RESULT

DRASTIC_DATA_FOLDER_A = DRASTIC_DATA_FOLDER + "a/"
DRASTIC_DATA_A_INPUT = DRASTIC_DATA_FOLDER_A + FOLDER_INPUT
DRASTIC_DATA_A_PROCESS = DRASTIC_DATA_FOLDER_A + FOLDER_PROCESS
DRASTIC_DATA_A_RESULT = DRASTIC_DATA_FOLDER_A + FOLDER_RESULT

DRASTIC_DATA_FOLDER_S = DRASTIC_DATA_FOLDER + "s/"
DRASTIC_DATA_S_INPUT = DRASTIC_DATA_FOLDER_S + FOLDER_INPUT
DRASTIC_DATA_S_PROCESS = DRASTIC_DATA_FOLDER_S + FOLDER_PROCESS
DRASTIC_DATA_S_RESULT = DRASTIC_DATA_FOLDER_S + FOLDER_RESULT

DRASTIC_DATA_FOLDER_T = DRASTIC_DATA_FOLDER + "t/"
DRASTIC_DATA_T_INPUT = DRASTIC_DATA_FOLDER_T + FOLDER_INPUT
DRASTIC_DATA_T_PROCESS = DRASTIC_DATA_FOLDER_T + FOLDER_PROCESS
DRASTIC_DATA_T_RESULT = DRASTIC_DATA_FOLDER_T + FOLDER_RESULT

DRASTIC_DATA_FOLDER_I = DRASTIC_DATA_FOLDER + "i/"
DRASTIC_DATA_I_INPUT = DRASTIC_DATA_FOLDER_I + FOLDER_INPUT
DRASTIC_DATA_I_PROCESS = DRASTIC_DATA_FOLDER_I + FOLDER_PROCESS
DRASTIC_DATA_I_RESULT = DRASTIC_DATA_FOLDER_I + FOLDER_RESULT

DRASTIC_DATA_FOLDER_C = DRASTIC_DATA_FOLDER + "c/"
DRASTIC_DATA_C_INPUT = DRASTIC_DATA_FOLDER_C + FOLDER_INPUT
DRASTIC_DATA_C_PROCESS = DRASTIC_DATA_FOLDER_C + FOLDER_PROCESS
DRASTIC_DATA_C_RESULT = DRASTIC_DATA_FOLDER_C + FOLDER_RESULT

DRASTIC_DATA_FOLDER_DRASTIC = DRASTIC_DATA_FOLDER + "drastic/"
DRASTIC_DATA_DRASTIC_PROCESS = DRASTIC_DATA_FOLDER_DRASTIC + FOLDER_PROCESS
DRASTIC_DATA_DRASTIC_RESULT = DRASTIC_DATA_FOLDER_DRASTIC + FOLDER_RESULT

GOD_DATA_FOLDER_G = GOD_DATA_FOLDER + "g/"
GOD_DATA_G_INPUT = GOD_DATA_FOLDER_G + FOLDER_INPUT
GOD_DATA_G_PROCESS = GOD_DATA_FOLDER_G + FOLDER_PROCESS
GOD_DATA_G_RESULT = GOD_DATA_FOLDER_G + FOLDER_RESULT

GOD_DATA_FOLDER_O = GOD_DATA_FOLDER + "o/"
GOD_DATA_O_INPUT = GOD_DATA_FOLDER_O + FOLDER_INPUT
GOD_DATA_O_PROCESS = GOD_DATA_FOLDER_O + FOLDER_PROCESS
GOD_DATA_O_RESULT = GOD_DATA_FOLDER_O + FOLDER_RESULT

GOD_DATA_FOLDER_D = GOD_DATA_FOLDER + "d/"
GOD_DATA_D_INPUT = GOD_DATA_FOLDER_D + FOLDER_INPUT
GOD_DATA_D_PROCESS = GOD_DATA_FOLDER_D + FOLDER_PROCESS
GOD_DATA_D_RESULT = GOD_DATA_FOLDER_D + FOLDER_RESULT

GOD_DATA_FOLDER_GOD = GOD_DATA_FOLDER + "god/"
GOD_DATA_GOD_INPUT = GOD_DATA_FOLDER_GOD + FOLDER_INPUT
GOD_DATA_GOD_PROCESS = GOD_DATA_FOLDER_GOD + FOLDER_PROCESS
GOD_DATA_GOD_RESULT = GOD_DATA_FOLDER_GOD + FOLDER_RESULT

SI_DATA_FOLDER_G = SI_DATA_FOLDER + "g/"
SI_DATA_G_INPUT = SI_DATA_FOLDER_G + FOLDER_INPUT
SI_DATA_G_PROCESS = SI_DATA_FOLDER_G + FOLDER_PROCESS
SI_DATA_G_RESULT = SI_DATA_FOLDER_G + FOLDER_RESULT

SI_DATA_FOLDER_R = SI_DATA_FOLDER + "r/"
SI_DATA_R_INPUT = SI_DATA_FOLDER_R + FOLDER_INPUT
SI_DATA_R_PROCESS = SI_DATA_FOLDER_R + FOLDER_PROCESS
SI_DATA_R_RESULT = SI_DATA_FOLDER_R + FOLDER_RESULT

SI_DATA_FOLDER_A = SI_DATA_FOLDER + "a/"
SI_DATA_A_INPUT = SI_DATA_FOLDER_A + FOLDER_INPUT
SI_DATA_A_PROCESS = SI_DATA_FOLDER_A + FOLDER_PROCESS
SI_DATA_A_RESULT = SI_DATA_FOLDER_A + FOLDER_RESULT

SI_DATA_FOLDER_T = SI_DATA_FOLDER + "t/"
SI_DATA_T_INPUT = SI_DATA_FOLDER_T + FOLDER_INPUT
SI_DATA_T_PROCESS = SI_DATA_FOLDER_T + FOLDER_PROCESS
SI_DATA_T_RESULT = SI_DATA_FOLDER_T + FOLDER_RESULT

SI_DATA_FOLDER_LU = SI_DATA_FOLDER + "lu/"
SI_DATA_LU_INPUT = SI_DATA_FOLDER_LU + FOLDER_INPUT + "lu.shp"
SI_DATA_LU_PROCESS = SI_DATA_FOLDER_LU + FOLDER_PROCESS
SI_DATA_LU_RESULT = SI_DATA_FOLDER_LU + FOLDER_RESULT + "lu.tif"

SI_DATA_FOLDER_SI = SI_DATA_FOLDER + "si/"
SI_DATA_SI_PROCESS = SI_DATA_FOLDER_SI + FOLDER_PROCESS
SI_DATA_SI_RESULT = SI_DATA_FOLDER_SI + FOLDER_RESULT + "si.tif"